### PR TITLE
bioin-1101 some changes that gil asked for

### PR DESCRIPTION
**Pull request by mayalevy**

### CODE REVIEW

**Review by gilhornung — APPROVED** [review]
LGTM!

**Comment by ilyasoifer** [comment]
@mayalevy - what is the status of this?

**Comment by gilhornung** [comment]
Ilya, she is waiting for me.

**Comment by gilhornung** [comment]
@mayalevy - I've re-run GLNexus in the same way that lead to the error with the previous compress gvcf.
With the new compressGVCF it passed without a problem.
You can merge

**Pull request merged**
