### PR TITLE
coverage analysis fix

### PR DESCRIPTION
**Pull request by kenissur**
fixed minimal contig length so that only non-weird contigs in hg38 will be considered (with the existing threshold coverage data is created for >300 contigs) + minor bugfix

### CODE REVIEW

**Review by ilyasoifer — CHANGES_REQUESTED** [review]
10M sounds too harsh for that (can we settle on 1M)? In the log space it is meeting in the middle :)

**Comment by kenissur** [comment]
That would include 23 more contigs, is that what you want?

chr19_GL949751v2_alt            False   1002683
chr19_GL949748v2_alt            False   1064304
chr19_GL949750v2_alt            False   1066390
chr19_KI270938v1_alt            False   1066800
chr19_GL949749v2_alt            False   1091841
chr7_KI270803v1_alt             False   1111570
chr5_KI270897v1_alt             False   1144418
chr14_KI270846v1_alt            False   1351393
chr17_KI270908v1_alt            False   1423190
chr14_KI270847v1_alt            False   1511111
chr5_GL339449v2_alt             False   1612928
chr17_GL000258v2_alt            False   1821992
chr16_KI270728v1_random         False   1872759
chr16_KI270853v1_alt            False   2659700
chr17_KI270857v1_alt            False   2877074
chr6_GL000252v2_alt             False   4604811
chr6_GL000255v2_alt             False   4606388
chr6_GL000250v2_alt             False   4672374
chr6_GL000253v2_alt             False   4677643
chr6_GL000251v2_alt             False   4795265
chr6_GL000254v2_alt             False   4827813
chr6_GL000256v2_alt             False   4929269
chr15_KI270905v1_alt            False   5161414
chr21                           True    46709983
chr22                           True    50818468
chrY                            True    57227415
chr19                           True    58617616
chr20                           True    64444167
chr18                           True    80373285
chr17                           True    83257441
chr16                           True    90338345
chr15                           True    101991189
chr14                           True    107043718
chr13                           True    114364328
chr12                           True    133275309
chr10                           True    133797422
chr11                           True    135086622
chr9                            True    138394717
chr8                            True    145138636
chrX                            True    156040895
chr7                            True    159345973
chr6                            True    170805979
chr5                            True    181538259
chr4                            True    190214555
chr3                            True    198295559
chr2                            True    242193529

**Comment by kenissur** [comment]
We could also go with:
`"_" not in name and "." not in name`
which would cover hg38 and hg19.

What do you think?

**Comment by ilyasoifer** [comment]
I am mostly thinking about non-human genomes or next format of a human genome where they can invent a different convention.  Why is it a problem to settle on 1M?

**Comment by kenissur** [comment]
Okay, left it at 1M....

**Review by ilyasoifer — APPROVED** [review]

**Pull request merged**
