### PR TITLE
adding system tests to cnv Rscripts

### PR DESCRIPTION
**Pull request by TammushB**

### CODE REVIEW

**Comment by TammushB** [comment]
Tests failed because conda enviorment is not available in the CI machine. 
Doesn't the CI generate a Dockerfile per PR?

**Comment by doron-st** [comment]
> @doron-st @ilyasoifer Tests failed because conda enviorment is not available in the CI machine. Doesn't the CI generate a Dockerfile as the environment per PR?

You need to create the environment in .github/workflows/*.yml

**Review by doron-st — COMMENTED** [review]
Looks good. please add rds to git lfs: [git lfs track "*.rds"]

**Comment by TammushB** [comment]
@doron-st all done: added rds to git lfd track, added cn.mops conda enviorment to .github/workflows. tests complete successfully. 
Please approve so we can merge this.

**Review by doron-st — COMMENTED** [review]
Hi Tammy!
The rds files are not tagged by github as git-lfs files.
Perhaps because you added them before the *.rds to .gitattributes?
Can you try to remove the commits and re-commit them all at once?
This should work: (please check that it does what you expect)
git reset HEAD^
git commit -a -m "<your message>"
git push -f

**Review by doron-st — APPROVED** [review]
LGTM

**Pull request merged**
