### PR TITLE
vcfbed submodule in ugbio_core

### PR DESCRIPTION
**Pull request by avigailmo**
ugbio pr: https://github.com/Ultimagen/ugbio-utils/pull/69

### CODE REVIEW

**Review by TammushB — APPROVED** [review]
looks good. thanks1

**Review by TammushB — CHANGES_REQUESTED** [review]
CI fails :/
I guess you need to first merge ugbio to master and then it will pass.

**Comment by avigailmo** [comment]
> CI fails :/ I guess you need to first merge ugbio to master and then it will pass.

I don't want to merge because you're still working on the ugbio pr

**Comment by TammushB** [comment]
> > CI fails :/ I guess you need to first merge ugbio to master and then it will pass.
> 
> I don't want to merge because you're still working on the ugbio pr

I will rebase on master once merged and continue the work on my featuremap PR.

**Review by TammushB — APPROVED** [review]

**Pull request merged**
